# SPDX-FileCopyrightText: 2026 Knitli Inc. <knitli@knitli.com>
# SPDX-License-Identifier: MIT OR Apache-2.0
# NOTE: SPDX identifiers at the top of a file apply only to that file.
# The [Marque License 1.0 (SPDX-License-Identifier: LicenseRef-MarqueLicense-1.0)](./LICENSE.md) covers the project's source code and technical specs/plans.
# deny.toml — cargo-deny configuration
# https://embarkstudios.github.io/cargo-deny/

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]

# NOTE on licenses:
# -- this is here to save you the time of looking it up yourself --
# If you run `cargo deny list`, you will see `r-efi` with `LGPL-2.1` in the output.
# LGPL would probably not be a problem for us, but it is something to avoid if we can
#
# The graph looks like this:
# `marque` [dev dependency] -> `insta` -> `tempfile` -> `getrandom` -> `r-efi`
# `getrandom` only uses `r-efi` when the target os is `uefi` and the getrandom backend is `efi_rng`.
# so `r-efi` is not actually used in our build, and the license is not relevant to us.
# Why `cargo deny list` shows this, but doesn't error here is a mystery to me.
# If it can figure out we don't use it, why list it?
[licenses]
version = 2
allow = [
  "LicenseRef-MarqueLicense-1.0",
  "Apache-2.0",
  "Apache-2.0 WITH LLVM-exception",
  "MIT",
  "MIT-0",
  "BSD-2-Clause",
  "BSD-3-Clause",
  "ISC",
  "Unicode-3.0",
  "Unicode-DFS-2016",
  "Unlicense",
  "Zlib",
  "CC0-1.0",
  "CC-BY-4.0",
]
unused-allowed-license = "allow"
confidence-threshold = 0.93

[[licenses.clarify]]
crate = "marque"
expression = "LicenseRef-MarqueLicense-1.0"
license-files = [{ path = "LICENSE.md", hash = 0x7bcf31ff }]

[[licenses.clarify]]
crate = "marque-capco"
expression = "LicenseRef-MarqueLicense-1.0"
license-files = [{ path = "LICENSE.md", hash = 0x7bcf31ff }]

[[licenses.clarify]]
crate = "marque-config"
expression = "LicenseRef-MarqueLicense-1.0"
license-files = [{ path = "LICENSE.md", hash = 0x7bcf31ff }]

[[licenses.clarify]]
crate = "marque-core"
expression = "LicenseRef-MarqueLicense-1.0"
license-files = [{ path = "LICENSE.md", hash = 0x7bcf31ff }]

[[licenses.clarify]]
crate = "marque-engine"
expression = "LicenseRef-MarqueLicense-1.0"
license-files = [{ path = "LICENSE.md", hash = 0x7bcf31ff }]

[[licenses.clarify]]
crate = "marque-extract"
expression = "LicenseRef-MarqueLicense-1.0"
license-files = [{ path = "LICENSE.md", hash = 0x7bcf31ff }]

[[licenses.clarify]]
crate = "marque-ism"
expression = "LicenseRef-MarqueLicense-1.0"
license-files = [{ path = "LICENSE.md", hash = 0x7bcf31ff }]

[[licenses.clarify]]
crate = "marque-rules"
expression = "LicenseRef-MarqueLicense-1.0"
license-files = [{ path = "LICENSE.md", hash = 0x7bcf31ff }]

[[licenses.clarify]]
crate = "marque-scheme"
expression = "LicenseRef-MarqueLicense-1.0"
license-files = [{ path = "LICENSE.md", hash = 0x7bcf31ff }]

[[licenses.clarify]]
crate = "marque-server"
expression = "LicenseRef-MarqueLicense-1.0"
license-files = [{ path = "LICENSE.md", hash = 0x7bcf31ff }]

[[licenses.clarify]]
crate = "marque-test-utils"
expression = "LicenseRef-MarqueLicense-1.0"
license-files = [{ path = "LICENSE.md", hash = 0x7bcf31ff }]

[[licenses.clarify]]
crate = "marque-wasm"
expression = "LicenseRef-MarqueLicense-1.0"
license-files = [{ path = "LICENSE.md", hash = 0x7bcf31ff }]

[bans]
multiple-versions = "warn"
highlight = "all"

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index",]
allow-git = []
required-git-spec = "rev"
