[tools]
"cargo:cargo-audit" = "latest"
"cargo:cargo-deny" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-smart-release" = "latest"

git-cliff = "latest"
typos = "latest"
tombi = "latest"
rust = "nightly"
yq = "latest"

[settings]
auto_install = true
experimental = true
