# SPDX-FileCopyrightText: 2026 Knitli Inc. <knitli@knitli.com>
# SPDX-License-Identifier: MIT OR Apache-2.0
# NOTE: SPDX identifiers at the top of a file apply only to that file.
# The [Marque License (SPDX-License-Identifier: LicenseRef-MarqueLicense)](./LICENSE) covers the project's source code.
experimental_monorepo_root = true

[shell_alias]
mx = "mise exec --"
mr = "mise run"

[tools]
"cargo:cargo-audit" = "latest"
"cargo:cargo-deny" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:cargo-smart-release" = "latest"

git-cliff = "latest"
typos = "latest"
tombi = "latest"
rust = "nightly"
yq = "latest"

[settings]
auto_install = true
experimental = true
