# Classification grammar

portions = [
  "(U//PR/NF//SBU-NF)",
  "(U//FOUO)",
  "(U//NF//XD)",
  "(U//DCNI//REL TO USA, GBR//NNPI)",
  "(U//SSI)",
  "(TS//SI/TK-BLFH//SAR-BP 52X3//RS/NF)",
  "(TS//HCS-P CUPCA//REL TO USA, FVEY)",
  "(TS)",
  "(U)",
  "(C)",
  "(C//NF)",
  "(//NR//REL TO USA, NATO)",
  "(//FSM S//NF)",
  "(S//REL TO USA, UKR, FVEY, NATO//NF)",
  "(TS//SI-G ABCD//OC/REL TO USA, NOR)",
  "(//JOINT TS AUS CAN ITA USA//REL TO USA, AUS, CAN, ITA, EU)",
  "(//CTS//BOHEMIA//ATOMAL//OC/REL TO USA, NATO)",
  "(C//NF//ND)",
  "(C//RD//PR/NF)",
  "(//NS//REL TO USA, NATO)",
  "(TS//SI/TK-IDIT//RS/NF)",
  "(S//HCS-O//OC/NF)",
  "(S//NF)",
  "(S//FGI JPN KOR//NF)",
  "(TS//TFNI//REL TO USA, FVEY)",
  "(S//RAWFISA//NF)",
  "(S//FRD//REL TO USA, AUS, GBR)",
  "(S//RD-CNWDI//NF)",
  "(C//NF//ND)",
  "(S//SI//REL TO USA, FVEY)",
  "(S//PR/REL TO USA, EST)",
  "(TS//SI-FUN RANDY EMU//RD//OC-USGOV/NF/FISA)",
  "(TS//SI/TK//RS/REL TO USA, FVEY)",
  "(U//RELIDO//LD)",
  "(S//DISPLAY ONLY AFG)",
  "(//BEL TS//REL TO USA, BEL, NATO)",
  "(S//FGI GBR NZL//NF)",
  "(U//REL TO USA, AUSTRALIA_GROUP//LES)",
  "(C//TFNI)",
  "(C//REL TO USA, AUT, JPN, KOR, SWE, FVEY, NATO)",
]
