# SPDX-FileCopyrightText: 2026 Knitli Inc. <knitli@knitli.com>
# SPDX-License-Identifier: MIT OR Apache-2.0
# NOTE: SPDX identifiers at the top of a file apply only to that file.
# The [Marque License 1.0 (SPDX-License-Identifier: LicenseRef-MarqueLicense-1.0)](./LICENSE.md) covers the project's source code and technical specs/plans.
[tools]
pnpm = "11.0.3"
biome = "2.4.14"
node = "24.14.1"

[deps]
pnpm = { auto = true }

[settings]
[settings.node]
corepack = true

[settings.npm]
package_manager = "pnpm"
