//! marque-ism build script.
//!
//! Parses ODNI ISM specification files from `schemas/ISM-v2022-DEC/` and
//! generates Rust code into `OUT_DIR/`:
//!
//! - `values.rs`      — CVE enumeration tables (all valid token values)
//! - `validators.rs`  — Schematron-derived validation predicates
//! - `migrations.rs`  — deprecated marking → replacement mappings
//!
//! # Schema Layout (actual ODNI package structure)
//!
//! ```
//! schemas/ISM-v2022-DEC/
//!   CVE_ISM/          CVEnumISM*.xml — ISM-specific CVE enumerations (XML, JSON, CSV)
//!   CVE_ISMCAT/       CVEGenerated/CVEnumISMCAT*.{rnc,rng,xsd} — country trigraphs etc.
//!   Schema/           IC-ISM.xsd, ISM.rng, CVEGenerated/*.{xsd,rnc,rng}
//!   Schematron/       ISM_XML.sch, ISM_XML-*-phase.xsl, Lib/*.sch
//! ```
//!
//! For `values.rs`: parse every `CVE_ISM/CVEnumISM*.xml` (one file per CVE).
//! For `validators.rs`: parse `Schematron/ISM_XML.sch` and `Schematron/Lib/*.sch`.
//! For `migrations.rs`: derive from deprecated tokens in CVE XMLs + schema version comparison.
//!
//! Rerun triggers: any change to schema files or this build script.
//!
//! TODO: implement full CVE/XSD/Schematron parsing.
//! Currently emits placeholder generated files so the workspace compiles.

use std::{env, fs, path::Path};

const SCHEMA_VERSION: &str = "ISM-v2022-DEC";

fn main() {
    let schema_dir = Path::new("schemas").join(SCHEMA_VERSION);
    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set");
    let out_path = Path::new(&out_dir);

    // Rerun if schema files change.
    println!("cargo:rerun-if-changed=schemas/");
    println!("cargo:rerun-if-changed=build.rs");

    generate_values(out_path, schema_dir.as_path());
    generate_validators(out_path, schema_dir.as_path());
    generate_migrations(out_path, schema_dir.as_path());
}

fn generate_values(out: &Path, schema_dir: &Path) {
    let _cve_dir = schema_dir.join("CVE_ISM");
    let _ismcat_dir = schema_dir.join("CVE_ISMCAT").join("CVEGenerated");

    let content = r#"
// Generated by build.rs from CVE_ISM/CVEnumISM*.xml — DO NOT EDIT.
//
// TODO: replace placeholders with values parsed from actual ODNI CVE XML files.
// Each CVEnumISM*.xml contains <CVEnumeration><Value> elements.

/// All valid SCI control tokens from CVEnumISMSCIControls.xml.
pub static SCI_CONTROLS: &[&str] = &["SI", "TK", "HCS", "KDK", "RST"];

/// All valid dissemination control tokens from CVEnumISMDissem.xml.
pub static DISSEM_CONTROLS: &[&str] = &[
    "NOFORN", "RELIDO", "FOUO", "ORCON", "PROPIN",
    "FISA", "DSEN", "LIMDIS", "IMCON",
];

/// Country trigraphs valid in REL TO / FGI fields.
/// Source: CVE_ISMCAT/CVEGenerated/CVEnumISMCATRelTo.xsd (XSD enumeration).
pub static COUNTRY_TRIGRAPHS: &[&str] = &[
    "USA", "GBR", "AUS", "CAN", "NZL",
    "DEU", "FRA", "NLD", "BEL", "DNK",
];

/// ISM schema version this crate was compiled against.
pub const SCHEMA_VERSION: &str = "ISM-v2022-DEC";
"#;

    fs::write(out.join("values.rs"), content).expect("failed to write values.rs");
}

fn generate_validators(out: &Path, schema_dir: &Path) {
    let _sch = schema_dir.join("Schematron").join("ISM_XML.sch");
    let _lib = schema_dir.join("Schematron").join("Lib");

    let content = r#"
// Generated by build.rs from Schematron/ISM_XML.sch — DO NOT EDIT.
//
// TODO: replace placeholders with predicates derived from Schematron assertions.

/// Returns true if the classification level string is valid.
pub fn is_valid_classification(s: &str) -> bool {
    matches!(s, "U" | "C" | "S" | "TS" | "UNCLASSIFIED" | "CONFIDENTIAL" | "SECRET" | "TOP SECRET")
}
"#;

    fs::write(out.join("validators.rs"), content).expect("failed to write validators.rs");
}

fn generate_migrations(out: &Path, schema_dir: &Path) {
    let _xsd = schema_dir.join("Schema").join("IC-ISM.xsd");
    let _dissem = schema_dir.join("CVE_ISM").join("CVEnumISMDissem.xml");

    let content = r#"
// Generated by build.rs — DO NOT EDIT.
//
// Maps deprecated marking strings to their current replacements.
// TODO: derive from @deprecated annotations in CVE XML and IC-ISM.xsd.

/// (deprecated, replacement, capco_ref)
pub static DEPRECATED_MARKINGS: &[(&str, &str, &str)] = &[
    ("LIMDIS",  "RELIDO",  "CAPCO-2019-§3.4"),
    ("FOUO",    "CUI",     "CAPCO-2022-§2.1"),
    ("NF",      "NOFORN",  "CAPCO-2022-§3.2"),
];
"#;

    fs::write(out.join("migrations.rs"), content).expect("failed to write migrations.rs");
}
