# SPDX-FileCopyrightText: 2026 Knitli Inc. <knitli@knitli.com>
# SPDX-License-Identifier: MIT OR Apache-2.0
# NOTE: SPDX identifiers at the top of a file apply only to that file.
# The [Marque License 1.0 (SPDX-License-Identifier: LicenseRef-MarqueLicense-1.0)](../../LICENSE) covers the project's source code.
version = 1

[[annotations]]
path = [
  "schemas/",
]
precedence = "override"
SPDX-FileCopyrightText = "United States Government, Public Domain"
SPDX-License-Identifier = "LicenseRef-PublicDomain"

[[annotations]]
path = ["src/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Knitli Inc. <knitli@knitli.com>"
SPDX-License-Identifier = "LicenseRef-MarqueLicense-1.0"
