// SPDX-FileCopyrightText: 2026 Knitli Inc.
//
// SPDX-License-Identifier: LicenseRef-MarqueLicense-1.0

//! Leaf vocabulary types for the ISM attribute model.
//!
//! Houses the structural, generated-CVE, and classification leaf types
//! shared by [`crate::ParsedAttrs`], [`crate::CanonicalAttrs`], and
//! [`crate::ProjectedMarking`]. Mirrors the IC ISM XML attribute model.
//!
//! # Code generation
//! CVE enum variants (`SciControl`, `DissemControl`, `DeclassExemption`) are
//! generated by `build.rs` from ODNI CVE XML files and re-exported from
//! `crate::generated::values`.
//!
//! SAR is NOT code-generated — SAR program identifiers are agency-assigned
//! codewords, not a closed vocabulary. SAR is modeled structurally via
//! [`SarMarking`] / [`SarProgram`] / [`SarCompartment`].
//!
//! # Pivot types
//!
//! The pivot role is split across three types:
//!
//! - [`crate::ParsedAttrs`] (in `parsed.rs`) — borrowed parser output.
//! - [`crate::CanonicalAttrs`] (in `canonical.rs`) — owned rule input.
//! - [`crate::ProjectedMarking`] (in `projected.rs`) — page projection
//!   output.
//!
//! Parser output ([`crate::ParsedAttrs`]) is converted to
//! [`crate::CanonicalAttrs`] through `MarkingScheme::canonicalize`
//! (the sole production path; the CAPCO override lives in
//! `marque_capco::CapcoScheme::canonicalize`).

use crate::generated::values;

// Re-export generated enum types for convenience.
pub use values::{DeclassExemption, DissemControl, SciControl, SciControlBare};

mod aea;
mod classification;
mod country_code;
#[cfg(test)]
mod country_code_tests;
mod nato;
mod non_ic_dissem;
mod sar;
mod sci;
mod token;

pub use aea::{AeaMarking, AtomalBlock, FrdBlock, RdBlock};
pub use classification::{
    Classification, FgiClassification, FgiMarker, ForeignClassification, JointClassification,
    MarkingClassification,
};
pub use country_code::CountryCode;
pub use nato::{NatoClassification, NatoLevel};
pub use non_ic_dissem::NonIcDissem;
pub use sar::{SarCompartment, SarIndicator, SarMarking, SarProgram};
pub use sci::{NatoSap, SciCompartment, SciControlSystem, SciMarking};
pub use token::{TokenKind, TokenSpan};

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
mod tests {
    use super::*;
    use crate::canonical::CanonicalAttrs;

    #[test]
    fn classification_ord_is_restrictiveness() {
        assert!(Classification::Unclassified < Classification::Restricted);
        assert!(Classification::Restricted < Classification::Confidential);
        assert!(Classification::Confidential < Classification::Secret);
        assert!(Classification::Secret < Classification::TopSecret);
    }

    #[test]
    fn classification_banner_portion_round_trip() {
        for c in [
            Classification::Unclassified,
            Classification::Restricted,
            Classification::Confidential,
            Classification::Secret,
            Classification::TopSecret,
        ] {
            assert!(!c.banner_str().is_empty());
            assert!(!c.portion_str().is_empty());
        }
    }

    #[test]
    fn nato_us_equivalent_mapping() {
        assert_eq!(
            NatoClassification::CosmicTopSecret.us_equivalent(),
            Classification::TopSecret,
        );
        assert_eq!(
            NatoClassification::NatoSecret.us_equivalent(),
            Classification::Secret,
        );
        assert_eq!(
            NatoClassification::NatoRestricted.us_equivalent(),
            Classification::Restricted,
        );
    }

    /// `NatoClassification` is a 5-variant bare-class enum: it does not
    /// fuse classification with AEA/SCI sub-marking semantics. ATOMAL
    /// lives in [`AeaMarking::Atomal`]; BALK/BOHEMIA in
    /// [`SciControlSystem::NatoSap`].
    #[test]
    fn nato_banner_portion_round_trip() {
        for n in [
            NatoClassification::NatoUnclassified,
            NatoClassification::NatoRestricted,
            NatoClassification::NatoConfidential,
            NatoClassification::NatoSecret,
            NatoClassification::CosmicTopSecret,
        ] {
            assert!(!n.banner_str().is_empty());
            assert!(!n.portion_str().is_empty());
        }
    }

    #[test]
    fn us_classification_convenience_returns_us() {
        let attrs = CanonicalAttrs {
            classification: Some(MarkingClassification::Us(Classification::Secret)),
            ..Default::default()
        };
        assert_eq!(attrs.us_classification(), Some(Classification::Secret));
    }

    #[test]
    fn us_classification_convenience_returns_none_for_nato() {
        let attrs = CanonicalAttrs {
            classification: Some(MarkingClassification::Nato(NatoClassification::NatoSecret)),
            ..Default::default()
        };
        assert_eq!(attrs.us_classification(), None);
    }

    #[test]
    fn us_classification_convenience_returns_resolved_for_conflict() {
        let attrs = CanonicalAttrs {
            classification: Some(MarkingClassification::Conflict {
                us: Classification::TopSecret,
                foreign: Box::new(ForeignClassification::Nato(
                    NatoClassification::CosmicTopSecret,
                )),
            }),
            ..Default::default()
        };
        assert_eq!(attrs.us_classification(), Some(Classification::TopSecret));
    }
}
