# SPDX-FileCopyrightText: 2026 Knitli Inc. <knitli@knitli.com>
# SPDX-License-Identifier: Apache-2.0
# NOTE: SPDX identifiers at the top of a file apply only to that file.
# The [Marque License 1.0 (SPDX-License-Identifier: LicenseRef-MarqueLicense-1.0)](../../LICENSE.md) covers the project's source code.
version = 1

[[annotations]]
path = ["**/*.js", "**/*.ts", "**/*.html", "**/*.css", "**/*.md"]
precedence = "closest"
SPDX-FileCopyrightText = "Knitli Inc. <knitli@knitli.com>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["**/*.wasm"]
precedence = "aggregate"
SPDX-FileCopyrightText = "Knitli Inc. <knitli@knitli.com>"
SPDX-License-Identifier = "LicenseRef-MarqueLicense-1.0"

# CodeMirror 6
[[annotations]]
path = ["vendor.js"]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2018 by Marijn Haverbeke <marijn@haverbeke.berlin>, Adrian Heine <mail@adrianheine.de>, and others"
SPDX-License-Identifier = "MIT"
